service: blockChain-app-database-second

provider:
  name: aws
  runtime: nodejs14.x
  stage: dev
  region: eu-west-3
  memorySize: 128
  
package:
  exclude:    
    - src/**
    - notes/**

functions:
  app:
    handler: dist/app.handler
    events: 
      - http: 
          path: /
          method: ANY
          cors: true
      - http: 
          path: /{proxy+}
          method: ANY
          cors: true
